### PR TITLE
Kiel Recyclerview Adapter Builder integration.

### PR DESCRIPTION
**Pull request by ibrahimyilmaz**
Hi @AdamMc331 

I would like contribute your project by integrating minimalist RecyclerView Adapter Kiel.

To be honest, I would like to integrate it to `Pokedex` firstly but I though it is better idea to integrate a project which has more than 1 RecyclerView.

Your ideas and feedbacks are greatly appreciated. If you want, I would integrate kiel to `Pokedex` also.

Sincerely
Ibra

### CODE REVIEW

**Comment by AdamMc331** [comment]
Thanks for the contribution @ibrahimyilmaz ! I think the reason GitHub actions failed is because it's not running on my account so it can't access the Firebase secret. 

Do you know what Kotlin version Kiel is using? When I run unit tests on your branch, they fail, but I think that's because I'm using an experimental library in testing and maybe the fact that they're out of sync is causing issues?

**Comment by ibrahimyilmaz** [comment]
Hi @AdamMc331, 

`kiel` is using  Kotlin 1.4.0. I run `gradlew check` all seemed fine. I will also take a look at failing tests when I reach my comp. There should not be any effect because it provides same ViewHolder mechanism for Espresso Tests

**Comment by ibrahimyilmaz** [comment]
I have found what is going wrong by running 
```
gw app:dependencies
```
Libraries are using different coroutine and kotlin versions. Gradle somehow choses the one which does not have  `consumeAsFlow`.

The solution:

```
    configurations.all {
        resolutionStrategy {
            force "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion"
        }
    }
```
Screen Shot 2020-08-22 at 9 21 41 PM

**Comment by AdamMc331** [comment]
Ah good catch. Checking now! Once this is merged, I'll probably update the Kotlin and coroutines dependencies and see if it's still an issue.

**Comment by AdamMc331** [comment]
Hmm okay they pass when I run from the IDE but not when I run via command line. Probably an issue on my machine with the java version I use, I've seen stuff like this before.

Ran it on the emulator & manually tried a couple screens and it worked great. :) Thanks again.

**Comment by ibrahimyilmaz** [comment]
It is my pleasure. If you want I can easily integrate it to Pokedex.
Also do you have a plan to change channel to `StateFlow`?

**Comment by AdamMc331** [comment]
Nah don't worry about pokedex because I haven't really been spending much time with it recently. It's also just one RV. 

I don't think I'll be changing the channel implementation that you're mentioning here. Because `dismissEvent` is supposed to be a one time event and not really a "state" change, I think making it a channel makes sense.

**Comment by AdamMc331** [comment]
Also bumping a bunch of versions in #229 and that seems to be fixing the tests that weren't working earlier. 👍

**Pull request merged**
